# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmembership_branches'),
        ('products', '0003_product_deleted_at_product_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='products_pr_organiz_29ba31_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='products_pr_organiz_32c06c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'brand'], name='products_pr_organiz_7201b0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'sku'], name='products_pr_organiz_88bfd9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'created_at'], name='products_pr_organiz_9534a7_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='products_pr_organiz_61283d_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['organization', 'name'], name='products_pr_organiz_a372f0_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'sku'], name='products_pr_product_b3af96_idx'),
        ),
    ]
