# Generated by Django 6.1 on 2026-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_created_by_sale_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
