# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_branches_br_organiz_bd37a8_idx_and_more'),
        ('customers', '0004_customer_customers_c_organiz_292401_idx_and_more'),
        ('organizations', '0003_organizationmembership_branches'),
        ('products', '0004_product_products_pr_organiz_29ba31_idx_and_more'),
        ('sales', '0004_saleitem_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', '-paid_at'], name='sales_payme_organiz_0aaec7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', '-paid_at'], name='sales_payme_sale_id_722be9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='sales_payme_referen_dff0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status'], name='sales_sale_organiz_d17eae_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'branch'], name='sales_sale_organiz_355f29_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'customer'], name='sales_sale_organiz_99ae60_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'sale_date'], name='sales_sale_organiz_823382_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', '-created_at'], name='sales_sale_organiz_bedd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='sales_sale_sale_nu_99d8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product_variant'], name='sales_salei_sale_id_699e46_idx'),
        ),
    ]
