# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmembership_branches'),
        ('suppliers', '0003_supplier_deleted_at_supplier_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='suppliers_s_organiz_15d721_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'name'], name='suppliers_s_organiz_f6fc20_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'created_at'], name='suppliers_s_organiz_25c90e_idx'),
        ),
    ]
