# Generated by Django 6.1 on 2026-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING_STOCK', 'Opening stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('RETURN_IN', 'Return in'), ('RETURN_OUT', 'Return out')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventorystock',
            options={'ordering': ['organization', 'branch', 'product_variant', 'product']},
        ),
    ]
