# Generated by Django 6.1 on 2026-09-02 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_code_and_more'),
        ('inventory', '0004_inventorystock_product_variant_and_more'),
        ('organizations', '0001_initial'),
        ('products', '0002_product_brand_product_created_by_productcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorystock',
            name='unique_inventory_stock_per_branch_product',
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', True)), fields=('branch', 'product'), name='unique_inventory_stock_per_branch_product'),
        ),
    ]
