# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_branches_br_organiz_bd37a8_idx_and_more'),
        ('inventory', '0005_remove_inventorystock_unique_inventory_stock_per_branch_product_and_more'),
        ('organizations', '0003_organizationmembership_branches'),
        ('products', '0003_product_deleted_at_product_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['organization', 'branch'], name='inventory_i_organiz_276289_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['organization', 'product'], name='inventory_i_organiz_3d4693_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['organization', 'product_variant'], name='inventory_i_organiz_f82b59_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['branch', 'updated_at'], name='inventory_i_branch__bd9f05_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', '-created_at'], name='inventory_s_organiz_fe2066_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'branch', '-created_at'], name='inventory_s_organiz_5d4002_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'movement_type', '-created_at'], name='inventory_s_organiz_ac829a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
    ]
