# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_branches_br_organiz_bd37a8_idx_and_more'),
        ('organizations', '0003_organizationmembership_branches'),
        ('products', '0004_product_products_pr_organiz_29ba31_idx_and_more'),
        ('purchases', '0004_purchase_created_by_purchase_discount_amount_and_more'),
        ('suppliers', '0003_supplier_deleted_at_supplier_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'status'], name='purchases_p_organiz_c867d5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'branch'], name='purchases_p_organiz_c045d1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'supplier'], name='purchases_p_organiz_65b8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'order_date'], name='purchases_p_organiz_45df8d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', '-created_at'], name='purchases_p_organiz_70a847_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_number'], name='purchases_p_purchas_12ae8f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product'], name='purchases_p_purchas_00688d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product_variant'], name='purchases_p_purchas_71af2f_idx'),
        ),
    ]
