# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_deleted_at_branch_deleted_by_and_more'),
        ('organizations', '0003_organizationmembership_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='branches_br_organiz_bd37a8_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'name'], name='branches_br_organiz_5b86e5_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'created_at'], name='branches_br_organiz_228cde_idx'),
        ),
    ]
