# Generated by Django 6.1 on 2026-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_approved_by_expense_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='legacy_category',
            field=models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SALARY', 'Salary'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('SUPPLIES', 'Supplies'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
