# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_branches_br_organiz_bd37a8_idx_and_more'),
        ('expenses', '0005_expensecategory_deleted_at_and_more'),
        ('organizations', '0003_organizationmembership_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'status'], name='expenses_ex_organiz_37d180_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'branch'], name='expenses_ex_organiz_1ba6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'category'], name='expenses_ex_organiz_1e8d91_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'expense_date'], name='expenses_ex_organiz_974c03_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', '-created_at'], name='expenses_ex_organiz_be2ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_number'], name='expenses_ex_expense_2fef2f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['organization', 'is_active', 'is_deleted'], name='expenses_ex_organiz_0690fe_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['organization', 'name'], name='expenses_ex_organiz_91ce6a_idx'),
        ),
    ]
