# Generated by Django 6.1 on 2026-09-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_code_and_more'),
        ('organizations', '0002_alter_organizationmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='branches.branch'),
        ),
    ]
