# Generated by Django 6.1 on 2026-09-03 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_branches_br_organiz_bd37a8_idx_and_more'),
        ('notifications', '0003_auditlog'),
        ('organizations', '0003_organizationmembership_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', 'branch', '-created_at'], name='notificatio_organiz_1e268d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='notificatio_resourc_83cf28_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='notificatio_target__7d000d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='notificatio_request_724579_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'recipient', '-created_at'], name='notificatio_organiz_ab7ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['resource_type', 'resource_id'], name='notificatio_resourc_b66932_idx'),
        ),
    ]
